name: Lookup API
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  gcp_access:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
            create_credentials_file: true
            activate_credentials_file: true
            workload_identity_provider: 'projects/814936308484/locations/global/workloadIdentityPools/github/providers/github-provider'
            service_account: 'github-actions@playground-s-11-38cb6692.iam.gserviceaccount.com'
      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.3.0
      - name: set crdential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Run gcloud
        run: gcloud compute instances list --zones us-east4-c
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v4
      
  #     - name: Install Pipenv
  #       run: pip install pipenv --user

  #     - name: Run Lint on code
  #       run: make lint
      
  #     - name: Run lint on Dockerfile
  #       run: make docker-lint
  
  # security_checks:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v4
      
  #     - name: Install Pipenv
  #       run: pip install pipenv --user

  #     - name: Run Security Check on code
  #       run: make security
      
  #     - name: Build an image
  #       run: docker build -t lookup-app:${{ github.sha }} .
      
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@0.28.0
  #       with:
  #         image-ref: 'lookup-app:${{ github.sha }}'
  #         format: 'table'
  #         exit-code: '1'
  #         ignore-unfixed: true
  #         vuln-type: 'os,library'
  #         severity: 'CRITICAL,HIGH'
        