name: Lookup API
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  service: alertmanager

permissions:
  id-token: write
  contents: read

jobs:
  code_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      
      - name: Install Pipenv
        run: pip install pipenv --user

      - name: Run Lint on code
        run: make lint
      
      - name: Run lint on Dockerfile
        run: make docker-lint
        